### ISSUE TITLE
Why cannot I connect?

### ISSUE THREAD

**Issue by TheMetMan** [yuppity/unifi-video-api#26]
Very sorry, not really an issue, but I cannot connect to my camera.
I have tried _all_ the possible permutations you kindly show to connect, but I get the same error each time.
Here are the different settings as per your instructions, I have put my own key in from the Browser GUI, even generated new keys, but no good.
I can log into the camera in the browser with my username and password perfectly well.
```
uva = UnifiVideoAPI(username='myuser', password='mypassword', addr='10.1.1.150')
uva = UnifiVideoAPI(api_key='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', addr='10.1.1.150')
uva = UnifiVideoAPI(api_key='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', addr='10.1.1.150', check_ufv_version=False)
uva = UnifiVideoAPI(api_key='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', addr='10.1.1.150', port=7443, schema='https', verify_cert=False)
```
Here is one error message as an example:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_snapshot.py", line 14, in <module>
    uva = UnifiVideoAPI(api_key='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', addr='10.1.1.150',port=7443, schema='https', verify_cert=False)
  File "/home/francis/bin/PythonEnvironments/Py_UnifiCamera/lib/python3.8/site-packages/unifi_video/api.py", line 138, in __init__
    self._load_data(self.get(endpoints['bootstrap']))
  File "/home/francis/bin/PythonEnvironments/Py_UnifiCamera/lib/python3.8/site-packages/unifi_video/api.py", line 304, in get
    res = self._urlopen(req)
  File "/home/francis/bin/PythonEnvironments/Py_UnifiCamera/lib/python3.8/site-packages/unifi_video/api.py", line 228, in _urlopen
    return urlopen(req, context=self._ssl_context)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
```

Any ideas why this is happening?
Regards

**Comment by yuppity** [comment]
Are you sure you should be able to? If you can, install `netcat` and run

```
nc -vv UNIFIVI_VIDEO_IP UNIFI_VIDEO_PORT
```

You should see something similar to _Connection to [...] succeeded_.

**Comment by TheMetMan** [comment]
Thanks so much, @yuppity , for the quick response.
```
ping 10.6.77.150
PING 10.6.77.150 (10.6.77.150) 56(84) bytes of data.
64 bytes from 10.6.77.150: icmp_seq=1 ttl=64 time=2.08 ms
64 bytes from 10.6.77.150: icmp_seq=2 ttl=64 time=2.50 ms
64 bytes from 10.6.77.150: icmp_seq=3 ttl=64 time=2.67 ms
64 bytes from 10.6.77.150: icmp_seq=4 ttl=64 time=2.14 ms
```
then
```
nc -vv 10.6.77.150 7443
nc: connect to 10.6.77.150 port 7443 (tcp) failed: Connection refused
```
and
```
nc -vv 10.6.77.150 7080
nc: connect to 10.6.77.150 port 7080 (tcp) failed: Connection refused
```
My route:
```
route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         unifi.fsoft.nne 0.0.0.0         UG    100    0        0 eth0
10.6.77.0       0.0.0.0         255.255.255.0   U     0      0        0 eth0
unifi.fsoft.nne 0.0.0.0         255.255.255.255 UH    100    0        0 eth0
```
Very odd.....

**Comment by yuppity** [comment]
As far as I can see, it's either that

- `10.6.77.150` is UniFI Video but you've set it up to use ports different from the defaults (or you've got it behind NAT, on a different port)
- or `10.6.77.150` is not the machine UniFi Video is running on :)

Was the browser you mentioned used on the same machine? Check the URL: Is `10.6.77.150` correct? How about the port? Did you use a domain instead of an IP?

**Comment by TheMetMan** [comment]
Thanks, @yuppity, I must be getting senile! I was using the Camera IP, not the UniFi Video Server, how stupid!!!
Sorted....... And I am SO grateful for your help.
Regards

**Comment by yuppity** [comment]
No worries :)
