### ISSUE TITLE
Trying to download the recording.

### ISSUE THREAD

**Issue by mdrobniu** [yuppity/unifi-video-api#31]
Hey. 

I've upgraded to 0.2.0 and I'm having issues with downloading recordings. 

I have tried this:
```
uva.recordings['60223fe0f650c88a5c8ae592'].download('rec.mp4')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: '60223fe0f650c88a5c8ae592'
>>> uva.get_recordings()['60223fe0f650c88a5c8ae592'].download('rec.mp4')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'generator' object is not subscriptable
```

Thanks for all the help.

**Comment by yuppity** [comment]
Could you run

```python
from unifi_video import UnifiVideoAPI
from datetime import datetime

OID_WANTED = '60223fe0f650c88a5c8ae592'

uva = UnifiVideoAPI(
    api_key='8mXZpaPS4KqaZRrDkoI8pO3OWJl42z3P',
    check_ufv_version=False,
    addr='192.168.2.43',
    port=7080)

oid_timestamp = int(OID_WANTED[:8], 16)
available_oids = uva.get('recording?idsOnly=true&sortBy=startTime&sort=desc&limit=0')['data']

recs = [r for r in uva.get_recordings() if r._id == OID_WANTED]
rec_ids = [oid for oid in available_oids if oid == OID_WANTED]
older_than_wanted = [
    ts for ts in [int(oid[:8], 16) for oid in available_oids]
    if ts < oid_timestamp
]

print('uva: {}, api: {}, api all: {}, older: {}'.format(
    len(recs),
    len(rec_ids),
    len(available_oids),
    len(older_than_wanted)))
```

and report what the last `print()` spits out.

**Comment by yuppity** [comment]
Could you run

```python
from unifi_video import UnifiVideoAPI
from datetime import datetime

OID_WANTED = '60223fe0f650c88a5c8ae592'

uva = UnifiVideoAPI(...)

oid_timestamp = int(OID_WANTED[:8], 16)
available_oids = uva.get('recording?idsOnly=true&sortBy=startTime&sort=desc&limit=0')['data']

recs = [r for r in uva.get_recordings() if r._id == OID_WANTED]
rec_ids = [oid for oid in available_oids if oid == OID_WANTED]
older_than_wanted = [
    ts for ts in [int(oid[:8], 16) for oid in available_oids]
    if ts < oid_timestamp
]

print('uva: {}, api: {}, api all: {}, older: {}'.format(
    len(recs),
    len(rec_ids),
    len(available_oids),
    len(older_than_wanted)))
```
and report what the last `print()` spits out.

**Comment by donaldrs** [comment]
this error for the first line indicates that the recording was not found. Try using

`uva.refresh_recordings(0)
uva.recordings['60223fe0f650c88a5c8ae592'].download('rec.mp4')`

If you still get the error, the recording was probably not available in the Unifi Video Server.

One extra "gotcha" is that when you download the video, the unifi server may not have finished, so you may get a partial video. In my code I check the expected length and compare it to the length of the downloaded video. If it is too short, I wait a bit and then try again.

**Comment by mdrobniu** [comment]
```
for rec in uva.get_recordings():
    print(rec)
....
UnifiVideoRecording: {'_id': '60265c69f650c88a5c8b3b62', 'rec_type': 'motionRecording', 'start_time': '2021-02-12T10:45:53', 'end_time': '2021-02-12T10:46:09'}
UnifiVideoRecording: {'_id': '60265f8ff650c88a5c8b3b6b', 'rec_type': 'motionRecording', 'start_time': '2021-02-12T10:59:19', 'end_time': '2021-02-12T10:59:45'}
>>> uva.recordings['60265f8ff650c88a5c8b3b6b'].download('rec.mp4')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: '60265f8ff650c88a5c8b3b6b'
>>> OID_WANTED = '60265f8ff650c88a5c8b3b6b'
>>> oid_timestamp = int(OID_WANTED[:8], 16)
>>> available_oids = uva.get('recording?idsOnly=true&sortBy=startTime&sort=desc&limit=0')['data']
>>>
>>> recs = [r for r in uva.get_recordings() if r._id == OID_WANTED]
>>> rec_ids = [oid for oid in available_oids if oid == OID_WANTED]
>>> older_than_wanted = [
...     ts for ts in [int(oid[:8], 16) for oid in available_oids]
...     if ts < oid_timestamp
... ]
>>>
>>> print('uva: {}, api: {}, api all: {}, older: {}'.format(
...     len(recs),
...     len(rec_ids),
...     len(available_oids),
...     len(older_than_wanted)))
uva: 1, api: 1, api all: 4947, older: 4946
>>>
```

**Comment by yuppity** [comment]
Thank you.

`uva.refresh_recordings()` will refresh the internal recordings collection while `uva.get_recordings()` will instead fetch an up-to-date recordings listing and return it as an iterable, giving no guarantee that the recordings
collection in the `UnifiVideoAPI` instance contains the same recordings. So, like @donaldrs suggested, you should `refresh_recordings()` before subscripting the internal collection:

> ```
> uva.refresh_recordings(0)
> uva.recordings['60223fe0f650c88a5c8ae592'].download('rec.mp4')
> ```

This ensures `uva.recordings` includes the latest recordings.

You cannot subscribe the iterable from `get_recordings()` with and ID as is. You'll have to resort to some sort of finagling. Couple of examples:

```python
rid = '60265f8ff650c88a5c8b3b6b'
list(filter(lambda x: x._id == rid, uva.get_recordings()))[0].download('rec.mp4')
```

or 

```python
rid = '60265f8ff650c88a5c8b3b6b'
{ v._id: v for v in uva.get_recordings() }[rid].download('rec.mp4')

```

and neither is any better than just doing

```python
for rec in uva.get_recordings():
  if rec._id == '60265f8ff650c88a5c8b3b6b':
    rec.download('rec.mp4')
```

I didn't anticipate a use case where you'd get a recording ID outside the context of iterating the internal collection. Maybe it'd make sense to write a separate method for that.

Please let me know if there is something I didn't address.

**Comment by mdrobniu** [comment]
Thank you guys. That works. !
